services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecret
      POSTGRES_USER: root
      POSTGRES_DB: simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:mysecret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
